name: X-WRT build

on:
  workflow_dispatch:
    inputs:
      SOURCE_TAG:
        description: '输入源码TAG'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get x-wrt source
        run: |
          sudo apt install -y build-essential ecj fastjar file flex g++ gcc-multilib g++-multilib gawk gettext git git-core java-propose-classpath libelf-dev libncurses5-dev libncursesw5-dev libssl-dev swig python3 python3-dev python3-distutils python3-pyelftools subversion unzip wget zlib1g-dev rsync qemu-utils
          wget "https://github.com/x-wrt/x-wrt/archive/refs/tags/${{ github.event.inputs.SOURCE_TAG }}.tar.gz"
          tar xvf ${{ github.event.inputs.SOURCE_TAG }}.tar.gz
          cd x-wrt-${{ github.event.inputs.SOURCE_TAG }}
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          mv ../.config ./
          sh feeds/x/rom/lede/fix-config.sh
          make -j1 V=s
          sleep 5s
          rm -rf ./bin/targets/ramips/mt7621/packages
          rm -f *-initramfs-kernel.bin

      - name : Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: x-wrt-${{ github.event.inputs.SOURCE_TAG }}
          path: x-wrt-${{ github.event.inputs.SOURCE_TAG }}/bin/targets/ramips/mt7621/
